export enum TEST_ID {
    WEATHER_CONDITION = 'WEATHER_CONDITION',
    CITY_FORM = 'CITY_FORM',
    SPINNER = 'SPINNER',
    TOOLTIP = 'TOOLTIP',
    ERROR_INDICATOR = 'ERROR_INDICATOR',
    WIDGET = 'WIDGET',
}; 